apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - deployment.yaml
configMapGenerator:
- name: nginx-ingress-error-page-source
  files:
    - source/index.html
    - source/nginx.conf