apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress-default-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jannik-Hm/Kube-Public'
    targetRevision: main
    path: 'config/nginx-ingress-default-backend/'
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
